server {
	listen 8080;
	host 127.0.0.1;
	max_body_size 5m;
	root /home/rmhazres/Desktop/webserv/tests_framework/data/www;
	index index.html;
	error_page 404 /home/rmhazres/Desktop/webserv/tests_framework/data/www/404.html;
	error_page 500 /home/rmhazres/Desktop/webserv/tests_framework/data/www/50x.html;

	location / {
		methods GET POST;
		index index.html;
	}

	location /static {
	methods GET;
	autoindex on;
	}

	location /upload {
		methods POST DELETE;
		upload_dir /home/rmhazres/Desktop/webserv/tests_framework/data/uploads;
	}

	location /cgi-bin {
		methods GET POST;
		cgi_extension .py;
		root /home/rmhazres/Desktop/webserv/tests_framework/data/www/cgi-bin;
	}
	location /exact {
		root /home/rmhazres/Desktop/webserv/tests_framework/data/www/exact_match;
		index exact.html;
		methods GET;
	}

	location /exact_match {
	root /home/rmhazres/Desktop/webserv/tests_framework/data/www/exact_match;
	index exact.html;
	methods GET;
	}

	location /static/nested {
		root /home/rmhazres/Desktop/webserv/tests_framework/data/www/static/nested;
		index nested.html;
		methods GET;
	}

	location /temp-redirect {
		redirect 302 /redirect-destination.html;
	}

	location /see-other {
		redirect 303 /redirect-destination.html;
	}



	location /temp-redirect-307 {
		redirect 307 /redirect-destination.html;
	}



	location /perm-redirect-308 {
		redirect 308 /redirect-destination.html;
	}



	location /redirect-with-query {
		redirect 301 /destination?param1=value1&param2=value2;
	}



	location /external-redirect {
		redirect 302 https://example.com/;
	}



	location /docs/old {
		redirect 301 /docs/new;
	}



	location /go-home {
		redirect 302 /;
	}



	location /redirect-chain-1 {
		redirect 302 /redirect-chain-2;
	}



	location /redirect-chain-2 {
		redirect 302 /redirect-chain-3;
	}

	location /redirect-chain-3 {
		index index.html;
		methods GET;
	}

	location /redirect-loop-1 {
		redirect 302 /redirect-loop-2;
	}

	location /redirect-loop-2 {
		redirect 302 /redirect-loop-1;
	}



	location /relative-redirect {
		redirect 302 ../other-page;
	}



	location /redirect-no-slash {
		redirect 301 /destination-no-slash;
	}



	location /redirect-with-slash {
		redirect 301 /destination-with-slash/;
	}

}