
        server {
            listen 8080;
            host localhost;
            root www;
        }
        server {
            listen 8080;
            host localhost;
            root www2;
        }
        