
        server {
            listen 8080;
            root www;
            
            location = /exact {
                index index.html;
            }
            
            location = /exact {
                index other.html;
            }
        }
        