
        server {
            listen 8080;
            root www;
            
            location /cgi-bin {
                cgi_handler php /usr/bin/php;
                methods GET POST;
            }
        }
        