
        server {
            listen 8080;
            root www;
            
            location / {
                index index.html;
                
                location /inner {
                    index inner.html;
                    
                    location /inner/deeper {
                        index deeper.html;
                        
                        location /inner/deeper/too-deep {
                            index too-deep.html;
                        }
                    }
                }
            }
        }
        