
        server {
            listen 8080;
            root www;
            
            location = /exact {
                index exact.html;
                
                location /nested { 
                    index nested.html;
                }
            }
        }
        