
            server {
                listen 8080;
                root www;
                
                location / {
                    redirect 301 /new-path;
                    upload /uploads;  # Should be incompatible with return
                }
            }
            