
            server {
                listen 8080;
                root www;
                
                location / {
                    redirect 301 /new-path;
                    autoindex on;
                }
            }
            