
        server {
            listen 8080;
            root www;
            
            location / {
                redirect 301 /redirect;
                root different/path;
            }
        }
        